#ifndef INT_HANDLERS_H_INCLUDED
#define INT_HANDLERS_H_INCLUDED

void do_isr0();
void do_isr1();
void do_isr2();
void do_isr3();
void do_isr4();
void do_isr5();
void do_isr6();
void do_isr7();
void do_isr8();
void do_isr9();
void do_isr10();
void do_isr11();
void do_isr12();
void do_isr13();
void do_isr14();
void do_isr15();
void do_isr16();
void do_isr17();
void do_isr18();
void do_isr19();
void do_isr20();
void do_isr21();
void do_isr22();
void do_isr23();
void do_isr24();
void do_isr25();
void do_isr26();
void do_isr27();
void do_isr28();
void do_isr29();
void do_isr30();
void do_isr31();
void do_isr32();
void do_isr33();
void do_isr34();
void do_isr35();
void do_isr36();
void do_isr37();
void do_isr38();
void do_isr39();
void do_isr40();
void do_isr41();
void do_isr42();
void do_isr43();
void do_isr44();
void do_isr45();
void do_isr46();
void do_isr47();

#endif // INT_HANDLERS_H_INCLUDED
